### ISSUE TITLE
Question about the training phases

### ISSUE THREAD

**Issue by L2-Zhang** [ml4bio/e2efold#14]
Hi. Your model is fantastic,especially the post processing part.

Do you have a try whether it's better to save the weight file and test short(<600)and long (600~1800) seqs independantly?

Thank you very much.

**Comment by liyu95** [comment]
Thank you very much for your interest!

I split the data into two parts mainly for save the memory and accelerate the program. In fact, one model for all the data also work well.

By the way, our group will release a new method very soon, which can outperform E2Efold by 25% on cross-dataset validation.

**Comment by L2-Zhang** [comment]
Thank you very much.
