### ISSUE TITLE
Prediction for user's input sequence

### ISSUE THREAD

**Issue by jaswindersingh2** [ml4bio/e2efold#2]
Hi,

Can you please make this algorithm to predict for user's input sequence? At the moment, it just works on the datasets that were used in the e2efold paper. It will be great if you can make this algorithm to give output in any standard RNA secondary structure format (like .dbn or .ct) for user's input sequence. 

Thank you

**Comment by lykaust15** [comment]
Hi,
Thank you very much for your suggestion! Yes, we will implement that part and upload that part soon.

**Comment by lykaust15** [comment]
For your information, we have uploaded part of the productive code. For the sequences longer than 600, we will upload the code by the end of this month. We are overwhelmed with deadlines, meetings, and interviews.

**Comment by jaswindersingh2** [comment]
Hi

Thank for your efforts to make it work for the user's input sequence. But when I run it on example sequence B01865.seq, the output .ct file is not showing any base-pair. I have attached the prediction file for the B01865.seq input sequence. On doing some debugging, it seems like on [line 129](https://github.com/ml4bio/e2efold/blob/9ddd6fba7d3aa43bab790c62e14dffa4289699b3/e2efold_productive/e2efold_productive_short.py#L129), the maximum predicted base probability was 0.2223, therefore on comparing with threshold > 0.5 no base-pair is detected. Can you please fix this issue?
[B01865.seq.ct.txt](https://github.com/ml4bio/e2efold/files/4631950/B01865.seq.ct.txt)

Thank you

**Comment by lykaust15** [comment]
Hi,

Could you double-check whether the model is load correctly? You need to download model files first and put them in the model folder.
In the shell output, you should have a line showing:
```'Loading e2e model...'```

**Comment by jaswindersingh2** [comment]
Hi 

Thank for the quick reply. Yeah, it was an error regarding model loading. Downloading the model files again and solved the problem. It is working perfectly now. Again, thank you very much.
