### ISSUE TITLE
Unpaired bases

### ISSUE THREAD

**Issue by mehdi1902** [ml4bio/e2efold#3]
Hi. I couldn't realize if you have considered unpaired bases in the measurement or not. Could you please explain it a bit? 
In fact, if base `i` should be unpaired in the structure, should we consider its prediction in the measurement or not? 

Thanks a lot in advance.

**Comment by lykaust15** [comment]
Hi, thank you very much for your interest!

> In fact, if base i should be unpaired in the structure, should we consider its prediction in the measurement or not?

We should. Unpaired is a status of pairing and we should be able to predict it.

>Hi. I couldn't realize if you have considered unpaired bases in the measurement or not. Could you please explain it a bit?

Yes, we considered that. For each position in the contact map, we considered it as a binary classification problem and made the evaluation accordingly. 

Here are the evaluation codes for your reference:
```
def evaluate_exact(pred_a, true_a):
    tp_map = torch.sign(torch.Tensor(pred_a)*torch.Tensor(true_a))
    tp = tp_map.sum()
    pred_p = torch.sign(torch.Tensor(pred_a)).sum()
    true_p = true_a.sum()
    fp = pred_p - tp
    fn = true_p - tp
    recall = tp/(tp+fn)
    precision = tp/(tp+fp)
    f1_score = 2*tp/(2*tp + fp + fn)
    return precision, recall, f1_score
```
