### ISSUE TITLE
Cannot reproduce e2efold_productive

### ISSUE THREAD

**Issue by kad-ecoli** [ml4bio/e2efold#4]
After setting up e2efold, including the pretrained models, I run e2efold by
```bash
cd e2efold_productive
bash main_long.sh
bash main_short.sh
```

To my surprise, even though e2efold_productive_short.py and e2efold_productive_long.py apparently generates 
```bash
long_cts/AB184819.seq.ct
long_cts/DQ170870.seq.ct
short_cts/B01865.seq.ct
short_cts/tdbD00012019.seq.ct
```
All the newly generated ct files contains no base pairs (0 at column 5). I have checked
``a_pred_list[-1].cpu()`` in ``e2efold_productive_short.py`` and found that all the values are <0.5, while only base pairs with ``a_pred_list[-1].cpu()>0.5`` are called base pairs. Why does my prediction all have such a low predicted probability?

I have attached the predicted ct files from my run of e2efold_productive
[ct.zip](https://github.com/ml4bio/e2efold/files/4782166/ct.zip)

**Comment by liyu95** [comment]
Hi, thank you very much for your interest!
Could you please refer to this issue (https://github.com/ml4bio/e2efold/issues/2) and make sure the model is loaded correctly?
In the shell output, you should have a line showing:
```Loading e2e model...```

**Comment by kad-ecoli** [comment]
Do you might uploading the model pt files to github? I guess downloading binary files from google drive may be the issue.

**Comment by liyu95** [comment]
Hi, it's not a good idea to involve models into the git. Every time you train a new model, the binary will change.
I did not encounter too much issues to use gdrive for storing binary before.
Again, please make sure you load the model correctly.

**Comment by kad-ecoli** [comment]
If you are worried about changing models, you can upload your model as part of the release (https://github.com/ml4bio/e2efold/releases). Anyway, at least I am not the only one having difficulty with google drive models.

**Comment by kad-ecoli** [comment]
After re-downloading the models, the program run through and generate the correct ct files.
